[ req ]
        default_bits           = 2048
        default_keyfile        = rootkeyfile.pem
        distinguished_name     = req_distinguished_name
        attributes             = req_attributes
        prompt                 = no
        output_password        = hjiFKt01

        [ req_distinguished_name ]
        C                      = IL
        ST                     = Ha-Merkaz
        L                      = Petah-Tikva
        O                      = adv
        OU                     = Distek Chem & PC Dev
        CN                     = advvcom
        emailAddress           = sai@distekgroup.com
[ req_attributes ]
        challengePassword              = password
